/**
 * Created by leon on 7/14/2020.
 */
public class LoopClass {
    public void doWhileLoop() {
        int counter = 0;
        do {
            System.out.println("Hello world");
            counter++;
        } while (counter < 5);
    }


    public void whileLoop() {
        int counter = 0;
        while (counter < 5) {
            System.out.println("Hello world");
        }
    }

    public void forLoop() {
        for (int i = 0; i < 5; i++) {
            System.out.println(i);
        }
    }


    public void itarLoop() {
        String[] someStringArray = new String[]{"The", "Quick", "Brown", "Fox"};
        String s = "Hey there world hey look hi how ya doing";
        s.replaceAll("H", "");

        // auto-generated by `itar` shortcut
        for (int i = 0; i < someStringArray.length; i++) {
            System.out.println(s);
        }
    }

    public void forEachLoop() {
        String[] someStringArray = "The Quick Brown Fox".split(" ");
        for (String eachElement : someStringArray) {
            System.out.println(eachElement);
        }
    }
}
