//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.10 at 10:08:43 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://perscholas.com/springboot/myboot/producingwebservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.perscholas.springboot.myboot.producingwebservice;
